#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ReindersMichaelAssn3.Resource", IsApplication=true)]

namespace ReindersMichaelAssn3
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int border_background = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05001d
			public const int btnAdventureCabinsSelect = 2131034141;
			
			// aapt resource value: 0x7f050002
			public const int btnCheckInDate = 2131034114;
			
			// aapt resource value: 0x7f050013
			public const int btnCheckInOutConfirm = 2131034131;
			
			// aapt resource value: 0x7f050029
			public const int btnCheckInOutSelect = 2131034153;
			
			// aapt resource value: 0x7f050003
			public const int btnCheckInTime = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int btnCheckOutDate = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int btnCheckOutTime = 2131034117;
			
			// aapt resource value: 0x7f050048
			public const int btnFinished = 2131034184;
			
			// aapt resource value: 0x7f05001c
			public const int btnJuniperSpringsSelect = 2131034140;
			
			// aapt resource value: 0x7f05001a
			public const int btnMainLodgeSelect = 2131034138;
			
			// aapt resource value: 0x7f050026
			public const int btnPersonalInfoSubmit = 2131034150;
			
			// aapt resource value: 0x7f050028
			public const int btnPersonalInformationSelect = 2131034152;
			
			// aapt resource value: 0x7f050034
			public const int btnRoomTypeConfirm = 2131034164;
			
			// aapt resource value: 0x7f05002a
			public const int btnRoomTypeSelect = 2131034154;
			
			// aapt resource value: 0x7f05002b
			public const int btnSpecialNeedsSelect = 2131034155;
			
			// aapt resource value: 0x7f05003a
			public const int btnSpecialNeedsSubmit = 2131034170;
			
			// aapt resource value: 0x7f05002c
			public const int btnSummarySelect = 2131034156;
			
			// aapt resource value: 0x7f05001b
			public const int btnSummitSelect = 2131034139;
			
			// aapt resource value: 0x7f050036
			public const int cbADA = 2131034166;
			
			// aapt resource value: 0x7f050038
			public const int cbSurcharge = 2131034168;
			
			// aapt resource value: 0x7f05002f
			public const int cbWknd = 2131034159;
			
			// aapt resource value: 0x7f050000
			public const int linearLayout1 = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int linearLayout2 = 2131034113;
			
			// aapt resource value: 0x7f050006
			public const int linearLayout3 = 2131034118;
			
			// aapt resource value: 0x7f05003b
			public const int linearLayout30 = 2131034171;
			
			// aapt resource value: 0x7f050007
			public const int linearLayout4 = 2131034119;
			
			// aapt resource value: 0x7f05000a
			public const int linearLayout5 = 2131034122;
			
			// aapt resource value: 0x7f05000d
			public const int linearLayout6 = 2131034125;
			
			// aapt resource value: 0x7f050010
			public const int linearLayout7 = 2131034128;
			
			// aapt resource value: 0x7f050014
			public const int linearLayout8 = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int linearLayout9 = 2131034133;
			
			// aapt resource value: 0x7f05001f
			public const int linearLayoutA = 2131034143;
			
			// aapt resource value: 0x7f050035
			public const int linearLayoutAB = 2131034165;
			
			// aapt resource value: 0x7f05002d
			public const int linearLayoutB = 2131034157;
			
			// aapt resource value: 0x7f050019
			public const int linearLayoutV = 2131034137;
			
			// aapt resource value: 0x7f050018
			public const int linearLayoutX = 2131034136;
			
			// aapt resource value: 0x7f050017
			public const int linearLayoutY = 2131034135;
			
			// aapt resource value: 0x7f050016
			public const int linearLayoutZ = 2131034134;
			
			// aapt resource value: 0x7f050032
			public const int rbExecutive = 2131034162;
			
			// aapt resource value: 0x7f050030
			public const int rbStandard = 2131034160;
			
			// aapt resource value: 0x7f050031
			public const int rbView = 2131034161;
			
			// aapt resource value: 0x7f050008
			public const int textViewCheckInDate = 2131034120;
			
			// aapt resource value: 0x7f05000b
			public const int textViewCheckInTime = 2131034123;
			
			// aapt resource value: 0x7f05000e
			public const int textViewCheckOutDate = 2131034126;
			
			// aapt resource value: 0x7f050011
			public const int textViewCheckOutTime = 2131034129;
			
			// aapt resource value: 0x7f050037
			public const int tvADA = 2131034167;
			
			// aapt resource value: 0x7f050046
			public const int tvADASummary = 2131034182;
			
			// aapt resource value: 0x7f050009
			public const int tvCheckInDate = 2131034121;
			
			// aapt resource value: 0x7f050040
			public const int tvCheckInSummary = 2131034176;
			
			// aapt resource value: 0x7f05000c
			public const int tvCheckInTime = 2131034124;
			
			// aapt resource value: 0x7f05000f
			public const int tvCheckOutDate = 2131034127;
			
			// aapt resource value: 0x7f050041
			public const int tvCheckOutSummary = 2131034177;
			
			// aapt resource value: 0x7f050012
			public const int tvCheckOutTime = 2131034130;
			
			// aapt resource value: 0x7f05001e
			public const int tvPersonalInfo = 2131034142;
			
			// aapt resource value: 0x7f050027
			public const int tvReservationNavigation = 2131034151;
			
			// aapt resource value: 0x7f050043
			public const int tvRoomPriceSummary = 2131034179;
			
			// aapt resource value: 0x7f050033
			public const int tvRoomTypeSelected = 2131034163;
			
			// aapt resource value: 0x7f050042
			public const int tvRoomTypeSummary = 2131034178;
			
			// aapt resource value: 0x7f05002e
			public const int tvRoomTypeText = 2131034158;
			
			// aapt resource value: 0x7f050047
			public const int tvSpecialNeedsSummary = 2131034183;
			
			// aapt resource value: 0x7f05003e
			public const int tvSummaryAddress = 2131034174;
			
			// aapt resource value: 0x7f05003f
			public const int tvSummaryHotel = 2131034175;
			
			// aapt resource value: 0x7f05003c
			public const int tvSummaryName = 2131034172;
			
			// aapt resource value: 0x7f05003d
			public const int tvSummaryPhone = 2131034173;
			
			// aapt resource value: 0x7f050045
			public const int tvSurcharge = 2131034181;
			
			// aapt resource value: 0x7f050044
			public const int tvWeekendRate = 2131034180;
			
			// aapt resource value: 0x7f050022
			public const int txtPersonalInfoAddress = 2131034146;
			
			// aapt resource value: 0x7f050023
			public const int txtPersonalInfoCity = 2131034147;
			
			// aapt resource value: 0x7f050020
			public const int txtPersonalInfoName = 2131034144;
			
			// aapt resource value: 0x7f050021
			public const int txtPersonalInfoPhone = 2131034145;
			
			// aapt resource value: 0x7f050024
			public const int txtPersonalInfoState = 2131034148;
			
			// aapt resource value: 0x7f050025
			public const int txtPersonalInfoZip = 2131034149;
			
			// aapt resource value: 0x7f050039
			public const int txtSpecialRequests = 2131034169;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CheckInOutSet = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int PersonalInformation = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ReservationNavigation = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int RoomType = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int SpecialNeeds = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Summary = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
